services:
  claude:
    image: lemonaderoom/claude-code:latest
    environment:
      FIGMA_API_KEY: ${FIGMA_API_KEY}
      GH_TOKEN: ${GH_TOKEN}
    ports:
      - '8080:8080'
    tty: true
    volumes:
      - ".:/claude/workspace"
      - "${HOME}/.claude:/claude/.claude"
      - "${HOME}/.claude.json:/claude/.claude.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
