services:
  claude:
    image: claude-code:latest
    build:
      context: .
    environment:
      FIGMA_API_KEY: ${FIGMA_API_KEY}
    ports:
      - '8080:8080'
    tty: true
    volumes:
      - ".:/claude/workspace"
      - "${HOME}/.claude:/claude/.claude"
      - "${HOME}/.claude.json:/claude/.claude.json"
