services:
  dev:
    image: lemonaderoom/claude-code:latest
    tty: true
    volumes:
      - "home:/claude"
      - ".:/claude/workspace"
      - "${HOME}/.claude:/claude/.claude"
      - "${HOME}/.claude.json:/claude/.claude.json"
      - "${HOME}/.gitconfig:/claude/.gitconfig"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  home: